name: "Lint and Test"

on:
  push:
    paths:
      - src/**
      - types/**
      - test/**
      - Gruntfile.js
      - .jshintrc
      - .jscsrc
      - .github/workflows/node-ci.yml
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - src/**
      - types/**
      - test/**
      - Gruntfile.js
      - .jshintrc
      - .jscsrc
      - .github/workflows/node-ci.yml
      - package.json
      - package-lock.json

jobs:

  build-and-test:

    name: "Build and test"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Set up Node"
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: "Install Node dependancies"
        run: |
          npm install

      - name: "Build project"
        run: |
          npx grunt

      - name: "Lint and coding style check with jshint and jscs"
        run: |
          npx grunt lint

      - name: "Test with mocha"
        run: |
          npx grunt test

